name: hive_shell
description: A powerful CLI interface to visualize and manage your Hive data without the need for a Flutter app.
version: 1.0.0
repository: https://github.com/fariosofernando/Hive_Shell

environment:
  sdk: ^3.1.0


dependencies:
  args: ^2.4.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
